name: Server CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted   # Uses your EC2 runner dice_fp_sapp_runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/dice_project_server_app:latest .

    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/dice_project_server_app:latest

    - name: Deploy on EC2
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_EC2_IP }}
        username: ubuntu
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        port: 22 
        script: |
          mkdir -p ~/server    # just for test
          docker rm -f dice_server || true
          docker pull muhammad0897979/dice_project_server_app:latest
          docker run -d \
            --name dice_server \
            -p 5000:5000 \
            -v servervol:/serverdata \
            muhammad0897979/dice_project_server_app:latest

    # - name: Slack notification
    #   uses: slackapi/slack-github-action@v1.23.0
    #   with:
    #     payload: |
    #       {
    #         "text": "âœ… Server container deployed successfully!"
    #       }
    #     webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
